import type { Metadata } from "next";
import "./globals.css";
import { Inter } from 'next/font/google';



const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: "My next js app",
  description: "Generated by create next app",
  keywords: 'Next.js, Typescript, React, Web Development',
  authors: [{ name: 'Your name'}],
  viewport: 'width=device-width, initial-scale=1'
};

export default function RootLayout({
  children,
}:{
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
    <body className={inter.className}>
    {children}
    </body>
    </html>
  );
}
